[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.18.0"
tokio = "1.17.0"
anyhow = "1.0.56"
log = "0.4.16"
env_logger = "0.9.0"
secp256k1 = "0.21.3"